package com.joy.datasource.model.discovery;

import java.util.Date;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.cover_path
     *
     * @mbggenerated
     */
    private String coverPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.parent_id
     *
     * @mbggenerated
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.order_num
     *
     * @mbggenerated
     */
    private Integer orderNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.is_checked
     *
     * @mbggenerated
     */
    private Boolean isChecked;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.is_deleted
     *
     * @mbggenerated
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.created_at
     *
     * @mbggenerated
     */
    private Date createdAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.updated_at
     *
     * @mbggenerated
     */
    private Date updatedAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.is_display
     *
     * @mbggenerated
     */
    private Boolean isDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.intro
     *
     * @mbggenerated
     */
    private String intro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.icon_version_id
     *
     * @mbggenerated
     */
    private Integer iconVersionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.selected_albums_switch
     *
     * @mbggenerated
     */
    private Boolean selectedAlbumsSwitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.is_finished
     *
     * @mbggenerated
     */
    private Boolean isFinished;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.category_type
     *
     * @mbggenerated
     */
    private Integer categoryType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.top_keyword_id
     *
     * @mbggenerated
     */
    private Integer topKeywordId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.is_metadata_exist
     *
     * @mbggenerated
     */
    private Boolean isMetadataExist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.is_upload_display
     *
     * @mbggenerated
     */
    private Boolean isUploadDisplay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_category.module_type
     *
     * @mbggenerated
     */
    private Integer moduleType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.id
     *
     * @return the value of tb_category.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.id
     *
     * @param id the value for tb_category.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.name
     *
     * @return the value of tb_category.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.name
     *
     * @param name the value for tb_category.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.title
     *
     * @return the value of tb_category.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.title
     *
     * @param title the value for tb_category.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.cover_path
     *
     * @return the value of tb_category.cover_path
     *
     * @mbggenerated
     */
    public String getCoverPath() {
        return coverPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.cover_path
     *
     * @param coverPath the value for tb_category.cover_path
     *
     * @mbggenerated
     */
    public void setCoverPath(String coverPath) {
        this.coverPath = coverPath == null ? null : coverPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.parent_id
     *
     * @return the value of tb_category.parent_id
     *
     * @mbggenerated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.parent_id
     *
     * @param parentId the value for tb_category.parent_id
     *
     * @mbggenerated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.order_num
     *
     * @return the value of tb_category.order_num
     *
     * @mbggenerated
     */
    public Integer getOrderNum() {
        return orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.order_num
     *
     * @param orderNum the value for tb_category.order_num
     *
     * @mbggenerated
     */
    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.is_checked
     *
     * @return the value of tb_category.is_checked
     *
     * @mbggenerated
     */
    public Boolean getIsChecked() {
        return isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.is_checked
     *
     * @param isChecked the value for tb_category.is_checked
     *
     * @mbggenerated
     */
    public void setIsChecked(Boolean isChecked) {
        this.isChecked = isChecked;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.is_deleted
     *
     * @return the value of tb_category.is_deleted
     *
     * @mbggenerated
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.is_deleted
     *
     * @param isDeleted the value for tb_category.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.created_at
     *
     * @return the value of tb_category.created_at
     *
     * @mbggenerated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.created_at
     *
     * @param createdAt the value for tb_category.created_at
     *
     * @mbggenerated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.updated_at
     *
     * @return the value of tb_category.updated_at
     *
     * @mbggenerated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.updated_at
     *
     * @param updatedAt the value for tb_category.updated_at
     *
     * @mbggenerated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.is_display
     *
     * @return the value of tb_category.is_display
     *
     * @mbggenerated
     */
    public Boolean getIsDisplay() {
        return isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.is_display
     *
     * @param isDisplay the value for tb_category.is_display
     *
     * @mbggenerated
     */
    public void setIsDisplay(Boolean isDisplay) {
        this.isDisplay = isDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.intro
     *
     * @return the value of tb_category.intro
     *
     * @mbggenerated
     */
    public String getIntro() {
        return intro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.intro
     *
     * @param intro the value for tb_category.intro
     *
     * @mbggenerated
     */
    public void setIntro(String intro) {
        this.intro = intro == null ? null : intro.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.icon_version_id
     *
     * @return the value of tb_category.icon_version_id
     *
     * @mbggenerated
     */
    public Integer getIconVersionId() {
        return iconVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.icon_version_id
     *
     * @param iconVersionId the value for tb_category.icon_version_id
     *
     * @mbggenerated
     */
    public void setIconVersionId(Integer iconVersionId) {
        this.iconVersionId = iconVersionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.selected_albums_switch
     *
     * @return the value of tb_category.selected_albums_switch
     *
     * @mbggenerated
     */
    public Boolean getSelectedAlbumsSwitch() {
        return selectedAlbumsSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.selected_albums_switch
     *
     * @param selectedAlbumsSwitch the value for tb_category.selected_albums_switch
     *
     * @mbggenerated
     */
    public void setSelectedAlbumsSwitch(Boolean selectedAlbumsSwitch) {
        this.selectedAlbumsSwitch = selectedAlbumsSwitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.is_finished
     *
     * @return the value of tb_category.is_finished
     *
     * @mbggenerated
     */
    public Boolean getIsFinished() {
        return isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.is_finished
     *
     * @param isFinished the value for tb_category.is_finished
     *
     * @mbggenerated
     */
    public void setIsFinished(Boolean isFinished) {
        this.isFinished = isFinished;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.category_type
     *
     * @return the value of tb_category.category_type
     *
     * @mbggenerated
     */
    public Integer getCategoryType() {
        return categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.category_type
     *
     * @param categoryType the value for tb_category.category_type
     *
     * @mbggenerated
     */
    public void setCategoryType(Integer categoryType) {
        this.categoryType = categoryType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.top_keyword_id
     *
     * @return the value of tb_category.top_keyword_id
     *
     * @mbggenerated
     */
    public Integer getTopKeywordId() {
        return topKeywordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.top_keyword_id
     *
     * @param topKeywordId the value for tb_category.top_keyword_id
     *
     * @mbggenerated
     */
    public void setTopKeywordId(Integer topKeywordId) {
        this.topKeywordId = topKeywordId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.is_metadata_exist
     *
     * @return the value of tb_category.is_metadata_exist
     *
     * @mbggenerated
     */
    public Boolean getIsMetadataExist() {
        return isMetadataExist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.is_metadata_exist
     *
     * @param isMetadataExist the value for tb_category.is_metadata_exist
     *
     * @mbggenerated
     */
    public void setIsMetadataExist(Boolean isMetadataExist) {
        this.isMetadataExist = isMetadataExist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.is_upload_display
     *
     * @return the value of tb_category.is_upload_display
     *
     * @mbggenerated
     */
    public Boolean getIsUploadDisplay() {
        return isUploadDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.is_upload_display
     *
     * @param isUploadDisplay the value for tb_category.is_upload_display
     *
     * @mbggenerated
     */
    public void setIsUploadDisplay(Boolean isUploadDisplay) {
        this.isUploadDisplay = isUploadDisplay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_category.module_type
     *
     * @return the value of tb_category.module_type
     *
     * @mbggenerated
     */
    public Integer getModuleType() {
        return moduleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_category.module_type
     *
     * @param moduleType the value for tb_category.module_type
     *
     * @mbggenerated
     */
    public void setModuleType(Integer moduleType) {
        this.moduleType = moduleType;
    }
}